version: "3"
services:
  elasticsearch:
    container_name: "elastic_training"
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    volumes:
      - $PWD/elasticsearch/config:/usr/share/elasticsearch/config
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
      - $PWD/elasticsearch/backups:/usr/share/elasticsearch/backups
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ELASTIC_PASSWORD=asecurepassword
    ports:
      - 9200:9200
    networks:
      elk-net:
        ipv4_address: 172.18.0.3
  
  kibana:
    container_name: "kibana_training"
    restart: always
    image: docker.elastic.co/kibana/kibana:8.1.1
    volumes:
      - $PWD/kibana/config:/usr/share/kibana/config
      - $PWD/kibana/data:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elk-net

  landing_page:
    container_name: "kibana_landing"
    restart: always
    image: luqmanr/es-api:0.0.1
    ports:
      - 8123:8123
    volumes:
      - $PWD/landing_page:/app
    working_dir: /app
    entrypoint: python3 server.py
    networks:
      - elk-net

  nginx:
    container_name: "nginx_training"
    restart: always
    image: nginx:alpine
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/log:/var/log/nginx
    ports:
      - 88:88
    networks:
      - elk-net

networks:
  elk-net:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/24"